version: "3.2"
services:
  springboot:
    build: 
      context: './springboot/'
    networks:
      - springnet
    ports:
      - "8080:8080"
    container_name: viki-springboot
  nginx:
    build:
      context: './nginx/'
    depends_on:
      - springboot
    networks:
      - springnet
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    container_name: viki-nginx
networks:
  springnet:
